### PR TITLE
Fixed typos, added translations for Spanish

### PR DESCRIPTION
**Pull request by Lonami**
Fixed typos (MInecraft, ....), added API translations, changed French
translation to Spanish.
There are still parts in French in the Spanish translation which should be checked!

### CODE REVIEW

**Comment by TheDoctorsLife** [comment]
Am Checking this now, will merge if everything is good.

**Comment by XyLoNaMiyX** [comment]
There are a lot of French translations, sadly, so it will take me a long while. But sure! I can do a bit everyday :)

**Comment by XyLoNaMiyX** [comment]
I think all the French parts have been removed from the Spanish translation! Ready to merge :)

**Comment by peterix** [comment]
I merged what I could into the current Spanish translation file. Hopefully it's good enough.

**Pull request closed without merging**
