### PR TITLE
Chinese translation for version 0.5.0

### PR DESCRIPTION
**Pull request by cqjjjzr**
Just a full translation of 0.5.0 in Chinese.

P.S. What happened to Weblate? I saw a low of invalid translation entries in the translation file.

### CODE REVIEW

**Comment by peterix** [comment]
A new release happened. I think the tooling keeps the old strings around, if the still sort of fit what's there.

**Comment by cqjjjzr** [comment]
Well I don't know what are you saying but i think it not's a good idea to use tool to generate template translation.

**Comment by peterix** [comment]
There is no other way to do it.

As part of a stable release, the translations are updated to match the new version:
http://ci.multimc.org/builders/translations-update/builds/10

And because this changes them, they are converted into the format MultiMC can download an use (this happens every time the translations change):
http://ci.multimc.org/builders/translations-build/builds/84

**Comment by peterix** [comment]
Let's look at it...

This is always generated:
https://github.com/MultiMC/MultiMC5-translate/blob/master/template.pot

And it seems that it is missing a few things...
https://github.com/MultiMC/MultiMC5/blob/develop/application/setupwizard/AnalyticsWizardPage.cpp#L67
I can't find AnalyticsWizardPage in `template.pot`.

Is this what you meant?

**Comment by peterix** [comment]
Anyway, the translations are updated based on the new `translate.pot`.

Things that were removed are commented out in the updated files:
https://github.com/MultiMC/MultiMC5-translate/blob/master/fr.po#L5243

So that seems to work as expected.

**Comment by peterix** [comment]
Opened https://github.com/MultiMC/MultiMC5/issues/1788 for the issue with missing strings.

**Comment by cqjjjzr** [comment]
My supposed way to handle translation problems is manually load strings from resource file and set the captions of components with them.

in Java I always do this:

`private JButton btnStartInstance;
................
 private JMenuItem mnuStartInstance;

..........................(many other things)

private void updateLabels() {
    ResourceBundle bundle = ResourceBundle.getResourceBundle("org.multimc.mainwindow");
    .............................................
    btnStartInstance.setText(bundle.getString("gui.startInstance"));
    mnuStartInstance.setText(bundle.getString("gui.startInstance"));
}`

there should be sth similar from this in Qt.

**Comment by peterix** [comment]
This is actually exactly what's happening. The only thing that's different is that the English text is used as the key, and the format used for the translations is optimized for size.

**Pull request merged**
