### PR TITLE
Update zh_TW.po

### PR DESCRIPTION
**Pull request by fanlan1210**

### CODE REVIEW

**Comment by cqjjjzr** [comment]
I skimmed and it's not bad. However I found some translation entries deleted. Could you please give it a look?

**Comment by peterix** [comment]
I don't really understand Chinese and all I have to check is automated translation tools...

I assume because the translations were marked as fuzzy and were no longer correct. I'd rather have no translation, than an incorrect one. However, if these should have been kept, then they should just lose the `fuzzy` tag and remain in the file.

**Comment by fanlan1210** [comment]
Reply @cqjjjzr : 
The translations which I deleted are incorrect.

Just as @peterix said:
> I'd rather have no translation, than an incorrect one. 

But I'll translate those soon. 😅

**Comment by cqjjjzr** [comment]
> The translations which I deleted are incorrect.

I'm really confused with the auto-generated incorrect translations. I don't know if this is caused by PoEdit or xgettext or something. Everytime I update the translation I found bad translation entries, and those entries have one thing in common: their translation are copied from those which have same English text as them.  
I believe this should be a bug.

Whatever, this translation is approved.

**Pull request merged**
