### PR TITLE
Update cs.po

### PR DESCRIPTION
**Pull request by 777misa**
Currently translated at 88,8% (574 of 617 strings)

### CODE REVIEW

**Comment by robotbrain** [comment]
Use translate.multimc.org instead of a PR

**Comment by 777misa** [comment]
I used translate.multimc.org. I didn´t know how to put it here.

**Comment by robotbrain** [comment]
An admin on the site can

**Comment by peterix** [comment]
I'm going to do this manually.

**Comment by peterix** [comment]
This is super outdated and super not useful anymore. I am sorry for letting this rot here for 3 years ~_~

**Pull request closed without merging**
